services:
  car-recognizer:
    build: .
    ports: 
      - 8000:8000
    volumes:
      - ./models/carPlateDetector.pt:/app/models/carPlateDetector.pt:ro
      - ./models/carModelRecognizer.pth:/app/models/carModelRecognizer.pth:ro