services:
  car-recognizer:
    build: .
    ports: 
      - 8000:8000
    volumes:
      - models/carPlateDetector.pt:models/carPlateDetector.pt:ro
      - models/carModelRecognizer.pkl:models/carModelRecognizer.pkl:ro